name: Publish NuGet Package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest  # Specify the GitHub runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the user's repository to the runner

      - name: Use NuGet Publisher Action
        uses: im-deviprakash/publishto_nuget@wokbr  # Replace with your action's repository and version
        with:
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}  # NuGet API Key (from GitHub Secrets)
          nuget_source: 'https://api.nuget.org/v3/index.json'  # Default NuGet source (can be customized if needed)
