name: Publish NuGet Package

on:
  workflow_dispatch:  # Manually triggerable workflow

jobs:
  publish:
    runs-on: ubuntu-latest  # Specify the GitHub runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checkout the user's repository to the runner

      - name: Publish .NET Library to NuGet
        uses: im-deviprakash/publishto_nuget@wokbr  # Replace with your action's repository and version
        with:
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}  # NuGet API Key (from GitHub Secrets)
          nuget_source: 'https://api.nuget.org/v3/index.json'  # Default NuGet source (can be customized if needed)
          repo_url: ${{ github.repository }}  # Pass the repository URL (using the current repo)
