name: Publish .NET Package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish to NuGet
        uses: your-username/your-repo-name@v1
        with:
          nuget_api_key: ${{ secrets.APIKEY_NUGET }}
          project_path: "Otp_Generation/Otp_Generation.csproj"
          version: ${{ github.event.inputs.version }}
